### ISSUE TITLE
[FEAT]: Docker image to run the tool in an air-gapped environment

### ISSUE THREAD

**Issue by hideintheclouds** [kocierik/k8s-to-diagram#4]
### Description

It would be useful to create a docker image with the required dependencies so that the tool can be executed in an air-gapped environment, or for those that do not have go environment setup

**Comment by kocierik** [comment]
thank you,
added [94f4e0e](https://github.com/kocierik/k8s-to-diagram/commit/94f4e0ed6619f6d9a372643d9328fdad2ba6761c)
